sudo: false

language: python - "2.7"

install:
    - pip install --user -r requirements.txt
    - export PATH=$HOME/.local/bin:$PATH

script:
    - git config --global user.email "travis"
    - git config --global user.name "travis"
    - git clone https://$GIT_TK@github.com/joaofcmota/siplab.git
    - mkdocs build
