# Main info
site_name: SIPLab @ Heriot-Watt
pages:
  - Signal and Image Processing Lab: index.md 
  - Yves Wiaux: yveswiaux.md
site_author: 'Joao Mota'
site_url: 'http://siplab.eps.hw.ac.uk'
theme_dir: 'theme'

# Copyright
copyright: 'Copyright &copy; 2017 Heriot-Watt University'

# Options
extra:
  #logo: 'images/logo.svg'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: false 

extra_css:
  - 'stylesheets/extra.css'
